name: 'Kubernetes toolset installer'
description: 'Github Action that install Kubernetes related tools very fast and cache them on the runner'
author: 'Yoichi Kawasaki @yokawasa'
inputs:
  kubectl:
    description: 'kubectl version'
  kustomize:
    description: 'kustomize version'
  helm:
    description: 'helm version'
  helmv3:
    description: 'helm3 version'
  kubeval:
    description: 'kubeval version'
  conftest:
    description: 'conftest version'
  rancher:
    description: 'rancher cli version'
  tilt:
    description: 'tilt version'
  skaffold:
    description: 'skaffold version'
outputs:
  kubectl-path:
    description: 'Path to the kubectl'
  kustomize-path:
    description: 'Path to the kustomize'
  helm-path:
    description: 'Path to the helm'
  helmv3-path:
    description: 'Path to the helmv3'
  kubeval-path:
    description: 'Path to the kubeval'
  conftest-path:
    description: 'Path to the conftest'
  yq-path:
    description: 'Path to the yq'
  rancher-path:
    description: 'Path to the rancher cli'
  tilt-path:
    description: 'Path to the tilt'
  skaffold-path:
    description: 'Path to the skaffold'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: docker
  image: Dockerfile
